[build]
  # Base directory where the package.json is located
  base = "artwork-gallery"
  
  # Build command with explicit steps and directory verification
  command = "npm ci && npm run build && echo 'Build completed, checking dist directory:' && ls -la dist && echo 'Dist directory contents verified'"
  
  # Directory to publish (relative to base directory)
  publish = "dist"

[build.environment]
  # Node.js version - updated for Vite compatibility
  NODE_VERSION = "20"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
