[build]
  # Base directory where the package.json is located
  base = "artwork-gallery"
  
  # Build command for Vite with verbose output
  command = "npm ci && npm run build"
  
  # Directory to publish (Vite's default output directory)
  publish = "artwork-gallery/dist"

[build.environment]
  # Node.js version - updated for Vite compatibility
  NODE_VERSION = "20"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
